/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Cape.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cape.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floating_Cape_1.geometry} material={materials.Material001} position={[1, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.808, 0.808, 1.454]} />
      <mesh geometry={nodes.Floating_Cape_2.geometry} material={materials.Cloth001} position={[-1, 0, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.67, 0.67, 1.205]} />
    </group>
  )
}

useGLTF.preload('/Cape.glb')
