/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 CapeB.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CapeB.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ground_Cape_1.geometry} material={materials.Cloth} scale={[0.834, 0.834, 1.501]} />
    </group>
  )
}

useGLTF.preload('/CapeB.glb')
