/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 eyeOrb.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eyeOrb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Material001} position={[0.278, 0, 0.005]} rotation={[0, -Math.PI / 2, 0]} scale={[1.165, 0.047, 1.165]} />
      <group position={[0.278, 0, 0.005]} rotation={[0, -Math.PI / 2, 0]} scale={0.891}>
        <mesh geometry={nodes.Sphere_1.geometry} material={materials.Material002} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials.RedEmissive} />
        <mesh geometry={nodes.Sphere_3.geometry} material={materials.Material003} />
      </group>
    </group>
  )
}

useGLTF.preload('/eyeOrb-transformed.glb')
