/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 SkullBat.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/SkullBat.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" position={[0, -4.096, -0.578]}>
          <primitive object={nodes.Bone004} />
          <skinnedMesh name="body002" geometry={nodes.body002.geometry} material={materials.Rock} skeleton={nodes.body002.skeleton} />
          <skinnedMesh name="membrane002" geometry={nodes.membrane002.geometry} material={materials.Lava} skeleton={nodes.membrane002.skeleton} />
          <skinnedMesh name="membrane003" geometry={nodes.membrane003.geometry} material={materials['membrane.001']} skeleton={nodes.membrane003.skeleton} />
        </group>
        <group name="Armature" position={[0, -4.066, 0.498]} scale={[0.75, 0.87, 0.75]}>
          <primitive object={nodes.Bone005} />
          <skinnedMesh name="body001" geometry={nodes.body001.geometry} material={materials.Rock} skeleton={nodes.body001.skeleton} />
          <skinnedMesh name="membrane" geometry={nodes.membrane.geometry} material={materials.Lava} skeleton={nodes.membrane.skeleton} />
          <skinnedMesh name="membrane001" geometry={nodes.membrane001.geometry} material={materials.Lava} skeleton={nodes.membrane001.skeleton} />
        </group>
        <group name="Jaw" rotation={[-Math.PI / 2, 0, 0]} scale={[0.031, 0.038, 0.038]}>
          <mesh name="Object_0001" geometry={nodes.Object_0001.geometry} material={materials.Rock} />
          <mesh name="Object_0001_1" geometry={nodes.Object_0001_1.geometry} material={materials.Ruby} />
        </group>
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials.Ice} position={[-0.369, 0.92, 0.85]} />
        <mesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={materials.Ice} position={[0.403, 0.92, 0.85]} />
        <group name="Skull001" rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
          <mesh name="Object_0003" geometry={nodes.Object_0003.geometry} material={materials.Ruby} />
          <mesh name="Object_0003_1" geometry={nodes.Object_0003_1.geometry} material={materials.Rock} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/SkullBat.gltf')
