/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Table.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Silver} scale={0.819} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} scale={0.819} />
    </group>
  )
}

useGLTF.preload('/Table-transformed.glb')
