/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 teardrop.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/teardrop-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, -1, 0]}>
          <primitive object={nodes.Bone} />
        </group>
        <skinnedMesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} skeleton={nodes.Sphere.skeleton} position={[0, -1, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/teardrop-transformed.glb')
