/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Torus.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Torus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus001.geometry} material={materials.Rock} scale={10} />
    </group>
  )
}

useGLTF.preload('/Torus.glb')
